# stages:          
#   - build
#   - test
#   - deploy

# build:       
#   stage: build
#   script:
#     - echo "Building tidepool helper"
#     - run pip install -r requirements.txt

run_tests:   
  stage: test   
  image: python:3.9-slim-buster 
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "Running tests"
    - pytest

# run_lint_tests:  
#   stage: test   
#   script:
#     - echo "Linting code... This will take about 10 seconds."
#     - sleep 10
#     - echo "No lint issues found."

# deploy:      
#   stage: deploy  
#   environment: production
#   script:
#     - echo "Deploying application..."
    # - echo "Application successfully deployed."
